options:
  domain:
    type: string
    default: ""
    description: |
      Provide registered domain name on which this site responding.
  tuning:
    type: string
    default: single
    description: | 
      This is the tuning level for the WordPress setup. There are three options: "bare", "single", and "optimized". "bare" will give you a nearly un-altered WordPress setup, as if you'd downloaded and set it up yourself. "single" will provide you with everything you need to run a singlular unit of WordPress. This doesn't take in to consideration that you'll be scaling at all. However, it will allow you to use WordPress free of any troubles and pesky limitations that typically happen during "optimized". While you _can_ scale out with this setting I encourage you read the README "optimized" will give you a hardened WordPress setup. Some of the features in the Admin panel will be locked down and theme edits/plugins can only be updated through he charm. This is the recommended setup for those who are in serious need of constant scaling. 
  wp-content:
    type: string
    default: ""
    description: | 
      This is a full repository or tar path to where the WordPress wp-contents can be found. At this time Git, BZR, SVN, and HG are supported also HTTP and HTTPS. An example of what a wp-content repository should look like can be found at http://github.com/jujutools/wordpress-site.
  engine:
    type: string
    default: apache
    description: "Currently two web server engines are supported: nginx and apache."
