#!/bin/sh -ex

source inc/common

tuning_level=`config-get tuning`
expose_info=`config-get debug`
engine=`config-get engine`
unit_address=`unit-get private-address`

tuning_level=${tuning_level,,}
expose_info=${expose_info,,}
engine=${engine,,}


if [ "$engine" == "apache" ] || [ "$engine" == "apache2" ]; then
	if [ -f .web-engine ]; then
		web_engine=`cat .web-engine`
		service $web_engine stop
	fi
	apt-get -y purge nginx
	apt-get --no-install-suggests --no-install-recommends install -y apache2-mpm-prefork libapache2-mod-php5
	service apache2 stop

  mkdir -p /srv/www/htdocs

  rm -f /etc/apache2/sites-available/*
	rm -f /etc/apache2/sites-enabled/*
	a2enmod actions rewrite alias headers php5

	juju-log "Installing Apache loadbal config..."
	install -o root -g root -m 0644 files/charm/apache/etc_apache2_sites-enabled_loadbalancer /etc/apache2/sites-available/loadbalancer
	sed -i -e "s/^  ServerName .*/  ServerName ${unit_address}/" /etc/apache2/sites-available/loadbalancer
	a2ensite loadbalancer

	juju-log "Installing Apache wordpress config..."
	install -o root -g root -m 0644 files/charm/apache/etc_apache2_sites-enabled_wordpress /etc/apache2/sites-available/wordpress
	a2ensite wordpress

	echo "apache2" > .web-engine
else
	if [ -f .web-engine ]; then
		web_engine=`cat .web-engine`
		service $web_engine stop
	fi
	apt-get -y purge apache2* libapache2*
	apt-get --no-install-suggests --no-install-recommends install -y nginx php5-fpm
	service nginx stop

	juju-log "Cleaning any old or default nginx site configs ..."
  rm -f /etc/nginx/sites-available/*
	rm -f /etc/nginx/sites-enabled/*
	rm -f /etc/nginx/conf.d/*

	juju-log "Installing nginx common config ..."
	rm -f /etc/nginx/nginx.conf
	install -o root -g root -m 0644 files/charm/nginx/etc_nginx_nginx.conf /etc/nginx/nginx.conf

	juju-log "Installing nginx actual site config ..."
	#rm -f /etc/nginx/sites-available/
	install -o root -g root -m 0644 files/charm/nginx/etc_nginx_sites-enabled_wordpress /etc/nginx/sites-available/wordpress
	ln -sf ../sites-available/wordpress /etc/nginx/sites-enabled/wordpress

	juju-log "Installing nginx loadbal config ..."
	rm -f /etc/nginx/sites-available/loadbalancer
	install -o root -g root -m 0644 files/charm/nginx/etc_nginx_sites-enabled_loadbalancer /etc/nginx/sites-available/loadbalancer
	ln -sf ../sites-available/loadbalancer /etc/nginx/sites-enabled/loadbalancer

	echo "nginx" > .web-engine
fi

hooks/loadbalancer-rebuild

juju-log "Restarting Services ..."
source hooks/restart

if [ ! -f $config_file_path ]; then
	juju-log "Nothing to configure, since nothing is installed"
	exit 0
fi

juju-log "I will be using this tuning level: $tuning_level"

if [ "$tuning_level" == "optimized" ]; then
	# First and foremost, we need to disable the ability to edit
	# themes and upload/update plugins. This breaks a scale-out
	# environment. It's sad but true. If you want to update a plugin
	# install a theme, etc; take a look at the README.
	make_optimized
elif [ "$tuning_level" == "single" ]; then
	# We need to prepare an NFS mount, because someone is probably
	# going to try to scale out. We also need to vamp up caching.
	make_single
elif [ "$tuning_level" == "bare" ]; then
	# Okay, you know what you're doing. You're probably going to
	# use Gluster to stream-line your files, so you don't need to
	# disable anything. We trust you to do what you need to.
	make_bare
else
	juju-log "Not sure about that tuning level."
	exit 1
fi

wp plugin update --path=$wp_install_path --all

do_cache

chown -R www-data.www-data $wp_install_path

. hooks/restart
