#!/bin/bash

set -xe

if [[ -d exec.d ]]; then
    shopt -s nullglob
    for f in exec.d/*/charm-pre-install; do
    [[ -x "$f" ]] || continue
    ${SHELL} -c "$f"|| {
        ## bail out if anyone fails
        juju-log -l ERROR "$f: returned exit_status=$? "
        exit 1
    }
    done
fi

add-apt-repository ppa:charmers/charm-helpers
apt-get update

apt-get --no-install-suggests --no-install-recommends -y install php5-memcache mysql-client pwgen php5 \
mailutils php-mail sysstat php5-mysql php5-mcrypt php5-memcache php5-curl rsync git-core mktemp \
php5-gd libssh2-php

juju-log "Creating random secret key ..."
if [ ! -f .wp-secret ]; then
	pwgen -s 10 1 > .wp-secret
fi

juju-log "Installing wp-cli to make this charm's life a little easier ..."
test -d /srv/www/wp-cli || git clone https://github.com/wp-cli/wp-cli.git /srv/www/wp-cli
# other hooks call hooks/install and don't expect the CWD to change so
# run this section in a subshell
(
	cd /srv/www/wp-cli
	# 20120926: v0.6.0 is confirmed working, so use it rather than alpha.
	git reset --hard v0.6.0
	git submodule update --init
	utils/dev-build
)

juju-log "So, environment is setup. We'll wait for some hooks to fire off before we get all crazy"
